version: '3'
services:
  mongodb:
    image: mongodb
    ports:
      - "27017:27017"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://mysql:3306/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5

  eureka-server:
    image: ms-eureka-server
    ports:
      - "9102:9102"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:9102/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5

  authentication-service:
    image: ms-authentication
    ports:
      - "9004:9004"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://authentication-service:9004/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5
    env_file:
      - .env

  gateway-management:
    image: ms-gateway
    ports:
      - "9002:9002"
    depends_on:
      authentication-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway-management:9002/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5
    env_file:
      - .env

  backend-patient-management:
    image: ms-backend-patient
    ports:
      - "9001:9001"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend-patient-management:9001/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5

  backend-note:
    image: ms-backend-note
    ports:
      - "9005:9005"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend-note:9005/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5

  backend-risk-assessment:
    image: ms-backend-risk
    ports:
      - "9006:9006"
    depends_on:
      eureka-server:
        condition: service_healthy
      backend-note:
        condition: service_healthy
      backend-patient-management:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend-risk-assessment:9006/actuator/health" ]
      interval: 15s
      timeout: 2s
      retries: 5

  frontend-management:
    image: ms-frontend
    ports:
      - "8080:8080"
    depends_on:
      gateway-management:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      backend-risk-assessment:
        condition: service_healthy
    env_file:
      - .env