version: '3'
services:
  mongodb:
    image: mongodb

  mysql:
    image: mysql
    ports:
      - "3306:3306"

  eureka-server:
    image: ms-eureka-server
    ports:
      - "9102:9102"

  gateway-management:
    image: ms-gateway
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server

  authentication-service:
    image: ms-authentication
    ports:
      - "9004:9004"
    depends_on:
      - eureka-server

  backend-patient-management:
    image: ms-backend-patient
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - mysql

  backend-note:
    image: ms-backend-note
    ports:
      - "9005:9005"
    depends_on:
      - eureka-server
      - mongodb

  backend-risk-assessment:
    image: ms-backend-risk
    ports:
      - "9006:9006"
    depends_on:
      - eureka-server
      - backend-patient-management
      - backend-note

  frontend-management:
    image: ms-frontend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mysql
      - eureka-server
      - gateway-management
      - backend-risk-assessment
      - backend-note
      - backend-patient-management
      - authentication-service

