spring:
  application:
    name: MS-GATEWAY

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/


#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: backend-patient-management
#          uri: lb://backend-patient-management
#          predicates:
#            - Path=/patients/**
#          filters:
#            - AddResponseHeader=X-Powered-By,Gio Gateway Service back
#
#        - id: front-route
#          uri: ${FRONT_ROUTE_URI:http://localhost:9002}
#          predicates:
#            - Path=/**
#          filters:
#            - AddResponseHeader=X-Powered-By,Gio Gateway Service front