spring:
  application:
    name: MS-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-BACKEND-PATIENT-MANAGEMENT
          uri: lb://MS-BACKEND-PATIENT-MANAGEMENT
          predicates:
            - Path=/patients/**
          filters:
            - AuthenticationFilter
        - id: MS-BACKEND-NOTE
          uri: lb://MS-BACKEND-NOTE
          predicates:
            - Path=/notes/**
          filters:
            - AuthenticationFilter
        - id: MS-ASSESSMENT-RISK
          uri: lb://MS-ASSESSMENT-RISK
          predicates:
            - Path=/risk-assessment/**
          filters:
            - AuthenticationFilter
        - id: MS-AUTH-SERVICE
          uri: lb://MS-AUTH-SERVICE
          predicates:
            - Path=/auth/**

  main:
    web-application-type: reactive

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/