spring:
  application:
    name: MS-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-BACKEND-PATIENT-MANAGEMENT
          uri: lb://MS-BACKEND-PATIENT-MANAGEMENT
          predicates:
            - Path=/patients/**
          filters:
            - AuthenticationFilter
        - id: MS-AUTH-SERVICE
          uri: lb://MS-AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
#  security:
#    user:
#      name: admin
#      password: admin

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/



#
#        - id: front-route
#          uri: ${FRONT_ROUTE_URI:http://localhost:9002}
#          predicates:
#            - Path=/**
#          filters:
#            - AddResponseHeader=X-Powered-By,Gio Gateway Service front